LANG    = Arabic
LCODE   = ar
COLUMNS = -c "Word, Roman (Word), Lemma, Roman (Lemma), Part of Speech, Gender, Case, Number, Person, Tense, Mood, Voice and Note"
OPTIONS = -1
TOPDIR  = ../..

all:

include ../word.mk
