LANG    = Hebrew
LCODE   = he
INITOPT = -n -c "Word, Roman (Word), Lemma, Roman (Lemma), Part of Speech, Gender, Case, Number, Person, Tense and Note"
OPTIONS = -1
TOPDIR  = ../..

all:

include ../common.mk
