LANG    = Ancient Greek
LCODE   = grc
INITOPT = -n -c "Word, Lemma, Part of Speech, Gender, Case, Number, Person, Tense, Mood, Voice and Note"
OPTIONS = -1
TOPDIR  = ../..

all:

include ../common.mk
