LANG    = Esperanto
LCODE   = eo
TOPDIR  = ../..
OPTIONS = -n 1 -f 0,4,3,1,5,2,6 -e "French, Latin, English, German, Italian, Greek"
# 1 English, 2 Italian, 3 Latin, 4 French, 5 German, 6 Ancient Greek

all:

include ../common.mk
