LANG    = Hindi
LCODE   = hi
COLUMNS = -c "Word, Roman (Word), Lemma, Roman (Lemma), Part of Speech, Gender, Case, Number, Person, Tense, Mood and Note"
OPTIONS = -1
TOPDIR  = ../..

all:

include ../word.mk
